version: 2
jobs:
  one:
    docker:
      - image: circleci/php:5.6.40-jessie
    steps:
      - checkout
      - run: |
        cd /tmp
        wget --no-verbose -O phpunit.phar https://phar.phpunit.de/phpunit-5.phar 
        chmod +x phpunit.phar
      - persist_to_workspace:
          root: /tmp
          paths:
            - phpunit.phar
  two:
    docker:
      - image: circleci/php:5.6.40-jessie
    steps:
      - checkout
      - attach_workspace:
          at: /tmp
      - run:  ls /tmp/phpunit.phar
workflows:
  version: 2
  one_an_two:
    jobs:
      - one
      - two:
          requires:
            - one
