version: 2
jobs:
  one:
    docker:
      - image: circleci/php:5.6.40-jessie
    steps:
      - checkout
      - run: |
          cd /tmp
          wget --no-verbose -O phpunit.phar https://phar.phpunit.de/phpunit-5.phar 
          chmod +x phpunit.phar
          mv phpunit.phar /usr/local/bin/phpunit
      - persist_to_workspace:
          root: /usr/local/bin
          paths:
            - phpunit
  two:
    docker:
      - image: circleci/php:5.6.40-jessie
    steps:
      - checkout
      - attach_workspace:
          at: /usr/local/bin
      - run: |
          ls /usr/local/bin/phpunit
          ls /usr/local/bin
workflows:
  version: 2
  one_an_two:
    jobs:
      - one
      - two:
          requires:
            - one
