version: 2
jobs:
  one:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run: echo "a first world"
      - run: mkdir -p my_workspace
      - run: echo "workspace mutation" > my_workspace/output
  two:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "more hello"
      - run: cat my_workspace/output
workflows:
  version: 2
  one_an_two:
    jobs:
      - one
      - two:
          requires:
            - one
